name = "marie"
license = "MIT"
licenselink = "https://github.com/jgeisslinger/hugo-marie/blob/master/LICENSE"
description = "A clean and resonsive bootstrap based Hugo Theme with a lot of configuration options"
homepage = "https://marie./"
tags = ["blog", "coding","clean"]
features = ["bootstrap", "responsive", "fontsize", "newsletter", "utterances", "files"]
min_version = "0.41.0"

[author]
  name = "Johannes Geisslinger"
  homepage = "https://coding.observer"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
